//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadisticas
    {
        public int EstadisticaId { get; set; }
        public int EquipoId { get; set; }
        public int Ganados { get; set; }
        public int Perdidos { get; set; }
        public int PuntosTotales { get; set; }
        public double DiferenciaPuntos { get; set; }
        public int PartidoId { get; set; }
        public int TemporadaId { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Partidos Partidos { get; set; }
        public virtual Temporada Temporada { get; set; }
    }
}
