//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugadores
    {
        public int JugadorId { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public int Numero { get; set; }
        public int EquipoId { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<int> Puntos { get; set; }
    
        public virtual Equipos Equipos { get; set; }
    }
}
