//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBP.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partidos()
        {
            this.Estadisticas = new HashSet<Estadisticas>();
        }
    
        public int PartidoId { get; set; }
        public System.TimeSpan Horario { get; set; }
        public int TemporadaId { get; set; }
        public int JornadaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int EquipoLocalId { get; set; }
        public int PuntosLocal { get; set; }
        public int EquipoVisitanteId { get; set; }
        public int PuntosVisitante { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Equipos Equipos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estadisticas> Estadisticas { get; set; }
        public virtual Jornadas Jornadas { get; set; }
        public virtual Temporada Temporada { get; set; }
    }
}
